### ISSUE TITLE
Docker didn't populate database

### ISSUE THREAD

**Issue by sjthespian** [TradeFace/gismocaster#55]
I'm trying to get this up and running under docker, but found that the initial startup didn't populate the database. I was able to get up and running by doing it manually, but there is no mention of this in the docs.

I ended up having to exec into the container and use manage.py as follows:
```
> docker exec -ti gismocaster /bin/bash
> make init
```

I would expect this to be done automatically on first startup if the database is empty, since I don't see any mention of it in the docs.

Here is the gismocaster section from my docker-compose config, the /etc and /var directories were copied from the git cloned data:
```
  gismocaster:
    ports:
      - "8000:8000"
    image: "gismocaster:latest"
    hostname: gismocaster
    container_name: gismocaster
    working_dir: /usr/src/app
    volumes:
      - /etc/gismocaster:/usr/src/app/etc
      - /var/gismocaster:/usr/src/app/var
    command: "python3 web/manage.py runserver 0.0.0.0:8000 --noreload"
    restart: always
    network_mode: host
```

One I ran a `make init`, things appear to be working fine.
